const fs=require('fs'),vm=require('vm'),assert=require('assert');const root=require('path').resolve(__dirname,'..')+'/';
function environment(initial={}){const storage={...initial},nodes={};const el=id=>nodes[id]??={value:({pool:'50 m',group:'Test Grubu',gap:'5',age:'13–16 Yaş',profile:'Orta Mesafe',session:'Salı Akşam',workoutDate:'2026-10-03'})[id]||'',style:{},options:id==='group'?[{value:'Test Grubu',textContent:'Test Grubu'}]:[],innerHTML:'',textContent:'',classList:{add(){},remove(){},contains(){return false}},appendChild(){}};const ctx={console,Date,Math,JSON,Promise,AbortController,document:{getElementById:el,querySelectorAll:()=>[]},localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},navigator:{onLine:true},requestAnimationFrame(){},setTimeout(){return 0},clearTimeout(){},setInterval(){},location:{},alert(){},prompt(){return null},addEventListener(){}};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'v18-data-core.js','utf8'),ctx);vm.runInContext(fs.readFileSync(root+'coach-set-guide.js','utf8'),ctx);return {ctx,storage,el,run:s=>vm.runInContext(s,ctx)}}
async function main(){
let e=environment(),{ctx,run,storage}=e;
ctx.KSData.addAthlete({name:'Test',stroke:'Kurbağalama',pb:{'50':{Kurbağalama:{25:20,50:42,100:90},Serbest:{25:15,50:30,100:66,200:140,400:300}}}});
let branch=ctx.KSData.workoutTarget('Test',{s:'Branş',z:'RP',d:100,send:150},'50');assert(branch&&branch.t===90);assert.equal(ctx.KSData.workoutTarget('Elif Gönül Acar',{s:'Branş',z:'RP',d:100},'50'),null);assert.equal(ctx.KSData.workoutTarget('Test',{s:'Kick',z:'A2',d:50},'50'),null);
let mixed=ctx.KSData.workoutTarget('Test',{s:'Branş',z:'SPR2',d:50,workDistance:25,returnDistance:25,send:240},'50');assert(mixed&&mixed.workTarget>20&&mixed.workTarget<21);assert(mixed.t>mixed.workTarget);assert.equal(mixed.split50,null);
let report={date:'2026-10-03',session:'Test',group:'Test Grubu',course:'50 m',created:'2026-10-03T14:00:00Z',finished:true,athletes:['Test'],results:Array.from({length:6},(_,i)=>({athlete:'Test',set:0,repeat:i+1,zone:'END2 • Serbest',stroke:'Serbest',distance:100,actual:'1:20.0',target:80,recordPerformance:true}))};ctx.KSData.storeReport(report);assert.equal(ctx.KSData.measuredHistory('Test','END2','50','Serbest').length,6);assert.equal(ctx.KSData.adaptation('Test','END2','50','Serbest').confidence,'medium');assert.equal(ctx.KSData.measuredHistory('Test','END2','50','Kurbağalama').length,0);
let mixReport={...report,session:'Split',results:[{athlete:'Test',set:0,repeat:1,zone:'SPR2 • Branş',stroke:'Kurbağalama',distance:50,elapsed:60,recordPerformance:false,workDistance:25,workElapsed:20.2,qualityTarget:20.2,qualityRecord:true}]};ctx.KSData.storeReport(mixReport);let measured=ctx.KSData.measuredHistory('Test','SPR2','50','Kurbağalama');assert.equal(measured.length,1);assert.equal(measured[0].distance,25);assert.equal(measured[0].elapsed,20.2);
// Failure at each write stage preserves the entire job; retry uses the same session code.
for(const failTable of ['live_sessions','live_arrivals','workout_history']){storage.ks_workout_upload_queue='[]';ctx.KSData.queueWorkout(report,[]);let codes=[],fail=true;const db={from(table){return {async upsert(row){if(table==='live_sessions')codes.push(row.code);if(fail&&table===failTable)return {error:{message:'simulated '+table}};return {error:null}}}}};let failed=await ctx.KSData.flushWorkoutQueue(db);assert.equal(failed.pending,1);const retained=JSON.parse(storage.ks_workout_upload_queue);assert(retained[0].lastError.includes('simulated'));fail=false;let good=await ctx.KSData.flushWorkoutQueue(db);assert.equal(good.pending,0);assert.equal(codes[0],codes[1]);assert.equal(JSON.parse(storage.ks_workout_history).length,2)}
// Reload and offline behavior; skip did-not-swim rows.
ctx.KSData.queueWorkout({...report,results:[...report.results,{athlete:'Test',repeat:7,set:0,actual:'YÜZMEDİ'}]},[]);const reloaded=environment(storage);reloaded.ctx.navigator.onLine=false;assert.equal((await reloaded.ctx.KSData.flushWorkoutQueue({})).pending,1);let calls=0;reloaded.ctx.navigator.onLine=true;await reloaded.ctx.KSData.flushWorkoutQueue({from(t){return {async upsert(){if(t==='live_arrivals')calls++;return {error:null}}}}});assert.equal(calls,6);
// A report revised while an upload is in flight remains queued.
storage.ks_workout_upload_queue='[]';ctx.KSData.queueWorkout(report,[]);let revised=false;await ctx.KSData.flushWorkoutQueue({from(t){return {async upsert(){if(!revised){revised=true;ctx.KSData.queueWorkout({...report,note:'new revision'},[])}return {error:null}}}}});assert.equal(JSON.parse(storage.ks_workout_upload_queue).length,1);
// Cloud fetch merging must not replace a pending local report.
const cloudDb={from(t){const result={data:t==='workout_history'?[{id:'cloud',workout_date:report.date,session:report.session,training_group:report.group,course:50,results:[],updated_at:'2026-10-04'}]:[],error:null};return {select(){return this},order(){return this},then(resolve){resolve(result)}}}};await ctx.KSData.syncCloud(cloudDb);assert(JSON.parse(storage.ks_workout_history).find(x=>x.session==='Test').results.length===6);
// Live screen, split button, canonical record and idempotent commit.
let payload={date:'2026-10-03',session:'Test',created:123,pool:'50 m',group:{name:'Test Grubu'},athletes:['Test'],sets:[{r:8,d:50,z:'SPR2',s:'Branş',send:240,workDistance:25,returnDistance:25,qualityRecord:true,recordPerformance:false,p:'25 hızlı + 25 kolay'}],targets:{0:{Test:mixed}}};storage.ks_v21_workout=JSON.stringify(payload);ctx.supabase={createClient:()=>({from(){return {async upsert(){return {error:{message:'offline'}}}}}})};
let live=fs.readFileSync(root+'v36-manual-pool.html','utf8').match(/<script>\(\(\)=>\{([\s\S]*)\}\)\(\);<\/script>/)[1];live=live.replace('renderPlan();tick();syncOffline().catch(()=>{});',"window.__test={commit,renderLive,loadDaily,repElapsed,set(values){if(values.arr)arr=values.arr;if(values.workArr)workArr=values.workArr},state(){return {plan,history,arr,workArr,si,rep}}};renderPlan();tick();");vm.runInContext('(()=>{'+live+'})();',ctx);ctx.__test.renderLive();assert(e.el('athletes').innerHTML.includes('25 m ÇALIŞMA'));ctx.__test.set({arr:{0:'1:00.0'},workArr:{0:20.2}});ctx.__test.commit();ctx.__test.commit();let state=ctx.__test.state();assert.equal(state.history.length,1);assert.equal(state.history[0].elapsed,60);assert.equal(state.history[0].workElapsed,20.2);assert.equal(state.history[0].zone,'SPR2');assert.equal(state.history[0].stroke,'Kurbağalama');let queue=JSON.parse(storage.ks_workout_upload_queue);assert(queue.length);ctx.__test.loadDaily();assert.equal(ctx.__test.state().history.length,1);assert.equal(ctx.__test.state().workArr[0],20.2);
ctx.__test.set({arr:{0:'TAMAMLANMADI'},workArr:{0:20.3}});ctx.__test.commit();assert.equal(ctx.KSData.measuredHistory('Test','SPR2','50','Kurbağalama').at(-1).elapsed,20.3);
// Pausing and resuming retains elapsed repeat time and arrivals.
let clock=Date.now(),oldNow=ctx.Date.now;ctx.Date.now=()=>clock;ctx.__test.set({arr:{0:'1:00.0'}});e.el('start').onclick();clock+=10000;assert.equal(ctx.__test.repElapsed(),10);e.el('start').onclick();clock+=5000;assert.equal(ctx.__test.repElapsed(),10);e.el('start').onclick();clock+=7000;assert.equal(ctx.__test.repElapsed(),17);assert.equal(ctx.__test.state().arr[0],'1:00.0');e.el('start').onclick();ctx.Date.now=oldNow;
// Missing branch data never fabricates a Serbest target in the live screen.
storage.v18Athletes=JSON.stringify([{name:'Test',stroke:'',pb:{'50':{Serbest:{100:60}}}}]);ctx.__test.renderLive();payload.targets={};storage.ks_v21_workout=JSON.stringify(payload);ctx.__test.loadDaily();ctx.__test.renderLive();assert(e.el('athletes').innerHTML.includes('Hedef verisi eksik'));
// Energy distribution and transition budget.
let day=fs.readFileSync(root+'v21-daily-workout.html','utf8').match(/<script>([\s\S]*)<\/script>/)[1];day=day.slice(0,day.indexOf('if(period){'));vm.runInContext(day,ctx);run("workout=[{r:8,d:50,workDistance:25,returnDistance:25,z:'SPR2',send:120,eq:'Palet'},{r:4,d:100,z:'A1',send:120,eq:'Yok'}]");const zones=run('zoneDistribution()');assert.equal(zones.raw.SPR2,200);assert.equal(zones.raw.A1,600);assert.equal(zones.total,800);assert.equal(run('transitionSeconds()'),90);assert.equal(run('workoutDuration().transitionMin'),1.5);
console.log('PASS: correct branş targets, missing-data behavior, canonical history/adaptation, separate work split, energy split, transitions, queue errors/retry/reload/revision, cloud merge, live commit/resume');
}
main().catch(e=>{console.error(e);process.exitCode=1});
